[project]
name = "ZypE"
version = "0.1.0"
description = "A small game made by CreeperIsASpy with love."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ursina>=7.0.0",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
